version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: com.googlecode.mp4parser:isoparser
    versions:
    - "> 1.0.6"
  - dependency-name: com.stripe:stripe-android
    versions:
    - "> 2.0.2"
  - dependency-name: cn.hutool:hutool-crypto
    versions:
    - 5.5.8
    - 5.5.9
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
  - dependency-name: cn.hutool:hutool-http
    versions:
    - 5.5.8
    - 5.5.9
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
  - dependency-name: cn.hutool:hutool-core
    versions:
    - 5.5.8
    - 5.5.9
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.3
  - dependency-name: com.google.firebase:firebase-crashlytics
    versions:
    - 17.4.0
  - dependency-name: androidx.core:core-ktx
    versions:
    - 1.5.0-beta02
    - 1.5.0-beta03
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.3-native-mt
  - dependency-name: com.google.android.play:core
    versions:
    - 1.10.0
  - dependency-name: com.google.firebase:firebase-crashlytics-gradle
    versions:
    - 2.5.0
    - 2.5.1
  - dependency-name: org.checkerframework:checker-qual
    versions:
    - 3.11.0
  - dependency-name: com.android.tools:desugar_jdk_libs
    versions:
    - 1.1.5
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.28"
  - dependency-name: junit:junit
    versions:
    - 4.13.2
